AWS_ACCESS_KEY_ID = AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
API_TOKEN = 3hr22ng35in593gwng2oegn2
PASSWORD = "NJI1LaeuC35O"
API_TOKEN_GOOGLE=ADI367192IE0ACE13AAA
